matrix:
- name: markdown
  dictionary:
    wordlists:
    - docs/spelling_wordlist
    output: _build/dictionary/python.dic
  sources:
  - 'docs/**/*.md'
  - README.md
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.toc
      - markdown.extensions.admonition
      - markdown.extensions.attr_list
      - pymdownx.superfences
      - pymdownx.blocks.admonition
      - pymdownx.blocks.caption
      - pymdownx.blocks.tab
      - pymdownx.details
  - pyspelling.filters.html:
      comments: true
      attributes:
        - title
        - alt
      ignores:
        - 'code'
        - 'pre'
        - 'div'
        - 'a'
        - 'nospell'
  - pyspelling.filters.context:
#      escapes: '\\[\\`~]'
      delimiters:
        # Ignore the Jinja directives
        - open: '{% '
          close: ' %}'
        # Ignores the autorefs link targets
        - open: '\]\['
          content: '[\d\D]*'
          close: '\]'
        # Ignore the single line Snippets syntax
        - open: '-8<- '
          content: '[\d\D]*'
          close: '\n'
        # Ignore the multiline Snippets syntax
        - open: '-8<-\n'
          close: '-8<-'
        # Ignore the multiline Snippets syntax
        - open: '-8<-\n\n'
          content: '[.\n]*?'
          close: '-8<-'
        # Ignore urls in frontmatter
        - open: '  url: https?:'
          close: '/$'
