authors:
  freakboy3742:
    name: Russell Keith-Magee
    short_name: Russell
    description: Founding Apiarist
    avatar: https://avatars.githubusercontent.com/u/37345
    url: https://cloudisland.nz/@freakboy3742
  kattni:
    name: Kattni
    short_name: Kattni
    description: Apiarist
    avatar: https://avatars.githubusercontent.com/u/7865090
    url: https://kattstodon.com/@kattni
  mhsmith:
    name: Malcolm Smith
    short_name: Malcolm
    description: Core Developer
    avatar: https://avatars.githubusercontent.com/u/166954
    url: https://github.com/mhsmith
  glasnt:
    name: Katie McLaughlin
    short_name: Katie
    description: 'TODO: Add.'
    avatar: 'TODO: Add.'
    url: https://cloudisland.nz/@glasnt
  phildini:
    name: 'TODO: Add.'
    short_name: 'TODO: Add.'
    description: 'TODO: Add.'
    avatar: 'TODO: Add.'
    url: 'TODO: Add.'
  hawkowl:
    name: 'TODO: Add.'
    short_name: 'TODO: Add.'
    description: 'TODO: Add.'
    avatar: 'TODO: Add.'
    url: 'TODO: Add.'
  danyeaw:
    name: 'TODO: Add.'
    short_name: 'TODO: Add.'
    description: 'TODO: Add.'
    avatar: 'TODO: Add.'
    url: 'TODO: Add.'
  rmartin16:
    name: 'TODO: Add.'
    short_name: 'TODO: Add.'
    description: 'TODO: Add.'
    avatar: 'TODO: Add.'
    url: 'TODO: Add.'
  swenson:
    name: 'TODO: Add.'
    short_name: 'TODO: Add.'
    description: 'TODO: Add.'
    avatar: 'TODO: Add.'
    url: 'TODO: Add.'
  BPYap:
    name: Yap Boon Peng
    short_name: 'TODO: Add.'
    description: 'TODO: Add.'
    avatar: 'TODO: Add.'
    url: 'TODO: Add.'
  adambonie:
    name: Adam Boniecki
    short_name: 'TODO: Add.'
    description: 'TODO: Add.'
    avatar: 'TODO: Add.'
    url: 'TODO: Add.'
  dayannefernandesc:
    name: Dayanne Fernandes
    short_name: 'TODO: Add.'
    description: 'TODO: Add.'
    avatar: 'TODO: Add.'
    url: 'TODO: Add.'
  ocupe:
    name: Jonas Schell
    short_name: 'TODO: Add.'
    description: 'TODO: Add.'
    avatar: 'TODO: Add.'
    url: 'TODO: Add.'
  kavi2du:
    name: Kavidu Abeykoon Mudiyanselagedara
    short_name: 'TODO: Add.'
    description: Curtin Capstone Team
    avatar: https://avatars.githubusercontent.com/u/132393780
    url: https://github.com/kavi2du
  Stringer90:
    name: Callum Horton
    short_name: 'TODO: Add.'
    description: Curtin Capstone Team
    avatar: https://avatars.githubusercontent.com/u/109891554
    url: https://github.com/Stringer90
  cadynn:
    name: Caydn Lee
    short_name: 'TODO: Add.'
    description: Curtin Capstone Team
    avatar: https://avatars.githubusercontent.com/u/104604345
    url: https://github.com/caydnn
  JMah007:
    name: Jaeden Mah
    short_name: 'TODO: Add.'
    description: Curtin Capstone Team
    avatar: https://avatars.githubusercontent.com/u/107184317
    url: https://github.com/JMah007
  mEp3ii2:
    name: Mitchell Pontague
    short_name: 'TODO: Add.'
    description: Curtin Capstone Team
    avatar: https://avatars.githubusercontent.com/u/74845700
    url: https://github.com/mEp3ii2
  vt37:
    name: Veronica Taniputra
    short_name: 'TODO: Add.'
    description: Curtin Capstone Team
    avatar: https://avatars.githubusercontent.com/u/110211722
    url: https://github.com/vt37
  patienceshyu:
    name: Patience Shyu
    short_name: 'TODO: Add.'
    description: 'TODO: Add.'
    avatar: 'TODO: Add.'
    url: 'TODO: Add.'
