authors:
  freakboy3742:
    name: Russell Keith-Magee
    short_name: Russell
    pronoun: he
    description: Founding Apiarist
    avatar: about/images/freakboy3742.png
    url: about/team/#freakboy3742
    join_date: 2013-09-05
    mastodon: "@freakboy3742@cloudisland.nz"
    email: russell@beeware.org
  kattni:
    name: Kattni
    short_name: Kattni
    pronoun: she
    description: Apiarist
    avatar: about/images/kattni.png
    url: about/team/#kattni
    join_date: 2025-10-05
    mastodon: "@kattni@kattstodon.com"
    email: kattni@beeware.org
  mhsmith:
    name: Malcolm Smith
    short_name: Malcolm
    pronoun: he
    description: Apiarist
    avatar: about/images/mhsmith.png
    url: about/team/#mhsmith
    join_date: 2022-08-31
    email: smith@chaquo.com
  glasnt:
    name: Katie McLaughlin
    short_name: Katie
    pronoun: they
    description: Senior Apiarist
    avatar: about/images/glasnt.png
    url: about/team/#glasnt
    join_date: 2016-04-02
    mastodon: "@glasnt@cloudisland.nz"
    email: katie@beeware.org
  phildini:
    name: Philip James
    short_name: Philip
    pronoun: he
    description: Senior Apiarist
    avatar: about/images/phildini.png
    url: about/team/#phildini
    join_date: 2016-06-03
    mastodon: "@phildini@wandering.shop"
    email: philip@beeware.org
  hawkowl:
    name: Amber Brown
    short_name: Amber
    pronoun: she
    description: Team Member Emeritus
    avatar: about/images/hawkowl.png
    url: about/team/#hawkowl
    join_date: 2016-10-13
    emeritus_date: 2025-12-15
    email: hawkowl@atleastfornow.net
  danyeaw:
    name: Dan Yeaw
    short_name: Dan
    pronoun: he
    description: Team Member Emeritus
    avatar: about/images/danyeaw.png
    url: about/team/#danyeaw
    join_date: 2018-02-28
    emeritus_date: 2021-05-01
    mastodon: "@danyeaw@fosstodon.org"
    email: dan@yeaw.me
  rmartin16:
    name: Russell Martin
    short_name: Russell M
    pronoun: he
    description: Apiarist
    avatar: about/images/rmartin16.png
    url: about/team/#rmartin16
    join_date: 2022-08-31
    email: rmartin16@gmail.com
  swenson:
    name: Christopher Swenson
    short_name: Swenson
    pronoun: they
    description: Team Member Emeritus
    avatar: about/images/swenson.png
    url: about/team/#swenson
    join_date: 2016-09-07
    emeritus_date: 2021-05-01
    mastodon: "@chris_swenson@tweets.icu"
    email: swenson@beeware.org
  halfwhitt:
    name: Charles Whittington
    short_name: Charles
    pronoun: they
    description: Apiarist
    avatar: about/images/halfwhitt.png
    url: about/team/#halfwhitt
    join_date: 2024-03-24
    email: charleswhitt@gmail.com
  cflee:
    name: Chiang Fong Lee
    short_name: Chiang Fong
    pronoun: he
    description: Team Member Emeritus
    avatar: about/images/cflee.png
    url: about/team/#cflee
    join_date: 2017-03-11
    emeritus_date: 2020-06-01
    mastodon: "@cflee@hachyderm.io"
    email: myself@cflee.net
  eliasdorneles:
    name: Elias Dorneles
    short_name: Elias
    pronoun: he
    description: Team Member Emeritus
    avatar: about/images/elias.png
    url: about/team/#eliasdorneles
    join_date: 2017-03-01
    emeritus_date: 2020-06-03
    email: eliasdorneles@gmail.com
  obulat:
    name: Olga Bulat
    short_name: Olga
    pronoun: she
    description: Team Member Emeritus
    avatar: about/images/obulat.png
    url: about/team/#obulat
    email: obulat@gmail.com
    join_date: 2018-03-05
    emeritus_date: 2025-12-05
  samschott:
    name: Sam Schott
    short_name: Sam
    pronoun: he
    description: Team Member Emeritus
    avatar: about/images/samschott.png
    url: about/team/#samschott
    email: sam.schott@outlook.com
    join_date: 2021-07-29
    emeritus_date: 2025-12-12
  flowerncsu:
    name: Charlotte Mays
    short_name: Charlotte
    pronoun: she
    description: Team Member Emeritus
    avatar: about/images/flowerncsu.png
    url: about/team/#flowerncsu
    mastodon: "@charlotte@hachyderm.io"
    email: charlotte@charlottemays.me
    join_date: 2017-08-17
    emeritus_date: 2025-12-15
  saroad2:
    name: Sagi Shadur
    short_name: Sagi
    pronoun: he
    description: Team Member Emeritus
    avatar: about/images/saroad2.png
    url: about/team/#saroad2
    email: saroad2@gmail.com
    join_date: 2020-05-31
    emeritus_date: 2025-12-15
  BPYap:
    name: Yap Boon Peng
    short_name: Boon Peng
    description: 2018 Google Summer of Code Student
    avatar: https://avatars.githubusercontent.com/u/32807097
    url: https://github.com/BPYap
  abonie:
    name: Adam Boniecki
    short_name: Adam
    description: 2017 Google Summer of Code Student
    avatar: https://avatars.githubusercontent.com/u/20281641
    url: https://github.com/abonie
  Dayof:
    name: Dayanne Fernandes
    short_name: Dayanne
    description: 2017 Google Summer of Code Student
    avatar: https://avatars.githubusercontent.com/u/8198348
    url: https://github.com/Dayof
  ocupe:
    name: Jonas Schell
    short_name: Jonas
    description: 2017 Google Summer of Code Student
    avatar: https://avatars.githubusercontent.com/u/11357413
    url: https://github.com/ocupe
  kavi2du:
    name: Kavidu Abeykoon Mudiyanselagedara
    short_name: Kavidu
    description: Curtin Capstone Team
    avatar: https://avatars.githubusercontent.com/u/132393780
    url: https://github.com/kavi2du
  Stringer90:
    name: Callum Horton
    short_name: Callum
    description: Curtin Capstone Team
    avatar: https://avatars.githubusercontent.com/u/109891554
    url: https://github.com/Stringer90
  cadynn:
    name: Caydn Lee
    short_name: Cadyn
    description: Curtin Capstone Team
    avatar: https://avatars.githubusercontent.com/u/104604345
    url: https://github.com/caydnn
  JMah007:
    name: Jaeden Mah
    short_name: Jaeden
    description: Curtin Capstone Team
    avatar: https://avatars.githubusercontent.com/u/107184317
    url: https://github.com/JMah007
  mEp3ii2:
    name: Mitchell Pontague
    short_name: Mitchell
    description: Curtin Capstone Team
    avatar: https://avatars.githubusercontent.com/u/74845700
    url: https://github.com/mEp3ii2
  vt37:
    name: Veronica Taniputra
    short_name: Veronica
    description: Curtin Capstone Team
    avatar: https://avatars.githubusercontent.com/u/110211722
    url: https://github.com/vt37
  patiences:
    name: Patience Shyu
    short_name: Patience
    description: 2018 Google Summer of Code Student
    avatar: https://avatars.githubusercontent.com/u/14033272
    url: https://github.com/patiences
  mikeckennedy:
    name: Michael Kennedy
    description: Resource author
    avatar: https://avatars.githubusercontent.com/u/2035561
    url: https://github.com/mikeckennedy
  akaptur:
    name: Allison Kaptur
    description: Resource author
    avatar: https://avatars.githubusercontent.com/u/1857780
    url: https://github.com/akaptur
  tonybaloney:
    name: Anthony Shaw
    description: Resource author
    avatar: https://avatars.githubusercontent.com/u/1532417
    url: https://github.com/tonybaloney
